Workaround for malformed search API result
Sometimes Twitter Search API returns JSON without `results` section.
This ends with the following error.

undefined method `map' for nil:NilClass (NoMethodError)
/app/vendor/bundle/ruby/1.9.1/gems/twitter-2.2.5/lib/twitter/client/search.rb:68:in `search'

With this patch, Twitter::Client::Search checks  content of `results`, and if
it is nil, return an empty array silently.